=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/issues/issue_051/issue_051.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" >

	<xs:element name="KeyValuePairs" type="KeyValuePairsType"/>
	<xs:complexType name="KeyValuePairsType">
		<xs:all>
			<xs:element type="xs:string" name="test2" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test3" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test4" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test5" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test6" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test7" minOccurs="0" maxOccurs="1" />
			<xs:element type="xs:string" name="test" minOccurs="1" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/issues/issue_051/issue_051.xml
<?xml version="1.0" encoding="UTF-8"?>
<KeyValuePairs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="issue_051.xsd">
	<test>root</test>
	<test2>root</test2>
	<test3>root</test3>
	<test4>root</test4>
	<test5>root</test5>
	<test6>root</test6>
	<test7>root</test7>
</KeyValuePairs>
