=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/issues/issue_035/dates.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="dates">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="row" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="string" type="xs:string"/>
							<xs:element name="day1" type="xs:int" minOccurs="0" maxOccurs="1"/>
							<xs:element name="day2" type="xs:int" minOccurs="0" maxOccurs="1"/>
							<xs:element name="month1" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="month2" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="year1" type="xs:int" minOccurs="0" maxOccurs="1"/>
							<xs:element name="year2" type="xs:int" minOccurs="0" maxOccurs="1"/>
							<xs:element name="periodicity" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="interim_number" type="xs:int" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/issues/issue_035/dates.xml
<?xml version="1.0"?>

<!--file structure>
		<string></string>
		<day1/>
		<day2/>
		<month1/>
		<month2/>
		<year1/>
		<year2/>
		<periodicity/>
		<interim_number/>
-->

<dates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="dates.xsd">
  <row>
    <string>2017-01-01</string>
    <day1>01</day1>
    <month1>01</month1>
    <year1>2017</year1>
  </row>
  <row>
    <string>2017-01-01 2017-12-31</string>
    <day1>01</day1>
    <day2>31</day2>
    <month1>01</month1>
    <month2>12</month2>
    <year1>2017</year1>
    <year2>2017</year2>
  </row>
  <row>
    <string>Q4 2017</string>
    <year1>2017</year1>
    <periodicity>Q</periodicity>
    <interim_number>4</interim_number>
  </row>
  <row>
    <string>abrakadabra costam costam 17</string>
    <abc></abc>
  </row>
</dates>
