=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/features/builtins/builtins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="ns" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="ns" >
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="birthdayDate" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="eventTime" type="xs:time" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="lastTicketDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/features/builtins/builtins.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:data xmlns:ns="ns"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="ns ./builtins.xsd">
    <birthdayDate>2005-05-25</birthdayDate>
    <birthdayDate>2001-01-01Z</birthdayDate>
    <birthdayDate>-0100-07-13</birthdayDate>
    <eventTime>00:00:00</eventTime>
    <eventTime>12:30:20.5555</eventTime>
    <eventTime>12:30:20-04:00</eventTime>
    <lastTicketDateTime>2017-09-06T23:59:00.000+03:00</lastTicketDateTime>
    <lastTicketDateTime>2017-09-06T23:59:00+03:00</lastTicketDateTime>
</ns:data>
