=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/issues/issue_073/issue_073.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:ns="ns" targetNamespace="ns">
  <element name="items" type="ns:sequenceType" />
  <complexType name="sequenceType">
    <sequence>
      <element type="string" name="a1" minOccurs="0" />
      <element type="string" name="a2" minOccurs="0" />
      <element type="string" name="a3" />
      <element type="string" name="a4" minOccurs="0" maxOccurs="unbounded" />
      <element type="string" name="a5" minOccurs="0" />
      <element type="string" name="a6" minOccurs="0" />
      <element type="string" name="a7" minOccurs="0" />
      <element type="string" name="a8" minOccurs="0" />
    </sequence>
  </complexType>
</schema>

=== rrosiek/pc_data_load/env/lib/python3.6/site-packages/xmlschema/tests/cases/issues/issue_073/issue_073-1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ns:items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:ns="ns" xsi:schemaLocation="ns issue_073.xsd">
    <a1>item1</a1>
    <a2>item2</a2>
    <a3>item3</a3>
    <a4>item3</a4>
    <a5>item3</a5>
    <a6>item3</a6>
    <a7>item3</a7>
    <a8>item3</a8>
</ns:items>
